### ISSUE TITLE
Benchmarking needed for the project 

### ISSUE THREAD

**Issue by glennawatson** [reactivemarbles/DynamicData#121]
To make it easier to track changes in the future bench marking of the various projects/classes is needed to make sure the project remains performant.

**Comment by glennawatson** [comment]
@onliner10 I can pick this one up if you like

**Comment by glennawatson** [comment]
As mentioned this task will likely use https://github.com/dotnet/BenchmarkDotNet

**Comment by onliner10** [comment]
@glennawatson that'd be great! I could focus then on optimizing the sort 
Ps. I already have some very simple  benchmarkdotnet setup on my branch, if that's of any help. However, I had problems running the benchmark as they sometimes just hang forever at more or less random step.. it could be due to AV software on my machine, however - didn't manage to resolve it yet

**Comment by glennawatson** [comment]
I sort of took over ReactiveUI project instead of going ahead with this one.. Sorry @RolandPheasant

**Comment by RolandPheasant** [comment]
Awesome for taking over Rui. Time for me to deal with it
