### ISSUE TITLE
Lack of Indexers in API

### ISSUE THREAD

**Issue by Noggog** [reactivemarbles/DynamicData#152]
Heya!  Enjoying the library so far.

I was wondering if there was a reason read-only indexers were omitted on classes like SourceList/Cache?  Seems like they could be exposed by drilling down to their internal ReaderWriters and getting the values.  Is there some issue I'm missing that inspired their absence?  I feel like even setters might be viable and just tie into the appropriate edit call.

**Comment by RolandPheasant** [comment]
The source cache has a method 'Lookup' which is effectively an indexer. I can't remember why I never added an indexer to the SourceList. Unless I can think of a reason not to, I will add one

**Comment by Noggog** [comment]
Awesome.  Yeah, seeing that now.

Perhaps it's just my old luggage coming along into new systems, but it would be nice to see all the familiar staples you'd expect in a Dictionary.  Stuff like TryGetValue, ContainsKey, etc.  I imagine it won't be 100% perfect enough to be able to actually implement IDictionary or anything, but having more of those concepts might be convenient to have

**Comment by reinux** [comment]
Did you ever recall why you decided against indexers?

**Comment by akervinen** [comment]
Any update on this? Currently I'm using either a binding or `list.Items.ElementAt`, but that copies the entire list on every access.

Adding a direct indexer to `SourceList` could also positively impact `ReactiveRecyclerViewAdapter`, since `GetViewModelByPosition` uses `list.Items.ElementAt`, copying the entire list every for every visible recycler item.
