### ISSUE TITLE
Aggregate operators start with initial value?

### ISSUE THREAD

**Issue by RandomEngy** [reactivemarbles/DynamicData#156]
I had this code (SubFolders and Items are `SourceList`s):

```c#
this.canRemoveFolderObservable = Observable.CombineLatest(
	this.SubFolders.Connect().Count(),
	this.Items.Connect().Count(),
	(numSubfolders, numItems) =>
	{
		return numSubfolders == 0 && numItems == 0 && this.Id != 0;
	});
```

It took me a long time to figure out why the combined observable never fired or even tried to compute the result. I eventually changed it to this:

```c#
this.canRemoveFolderObservable = Observable.CombineLatest(
	this.SubFolders.Connect().Count().StartWith(this.SubFolders.Count),
	this.Items.Connect().Count().StartWith(this.Items.Count),
	(numSubfolders, numItems) =>
	{
		return numSubfolders == 0 && numItems == 0 && this.Id != 0;
	});
```

Which did work. I kind of expected the aggregate operators to work like a "property" observable stream, and that I wouldn't need to kick-start manually with StartWith. Am I doing things wrong here?

**Comment by RolandPheasant** [comment]
By default Connect() is only invoked when there is something in the list (same for source cache) initially or after things have changed in the list.  The reason is to avoid empty change set notifications and subsequent operator handling as doing so can have serious performance implications.

That said, I see no reason not to modify the aggregation operators to ensure initial empty state is reflected. This would fix the issue

**Comment by rhy-ama** [comment]
@RolandPheasant your comment needs to make it to the front page / readme - as, in my experience, that design (while having the performance benefit you highlighted) is not intuitive and results - again in my experience, in hours or days lost tracking weird issues.

**Comment by glennawatson** [comment]
@rhy-ama Happy to take a PR to said readme as well.
