### ISSUE TITLE
How to use SourceList with Xamarin.Forms ListView grouping

### ISSUE THREAD

**Issue by imuller** [reactivemarbles/DynamicData#162]
Hi,

Before using SourceList i used the ReactiveList from ReactiveUI to group lists in lists. For example: 
`
var groups = new ReactiveList<Group>();`

Where the class Group derives from ReactiveList. When i try to change this to SourceList, i get this error: _cannot derive from sealed type SourceList<Item>_

**Old:**
`public class Group : ReactiveList<Item> { }`

**New (not working):**
`public class Group : SourceList<Item> { }`

**Comment by glennawatson** [comment]
Yeah. You may want to derive off `ObservableCollectionExtended` in this scenario instead. 

SourceList is a thread safe observable container that is meant for only inside as private in a class.  You then will `Bind()` to expose it via a `ReadOnlyObservableCollection` consumers. 

`ReactiveList` was never thread safe though and `ObserableCollectionExtended` is a close analog. 

You can then use the method `ToObservableChangeSet' to get observables about your derived class in this case.

**Comment by glennawatson** [comment]
It's a reactive aware object but not really consumable by non reactive aware objects such as the UI. So if you have need to expose it so you can use the change set observable that's the appropriate place. Most UI likes the INotifyCollevtionChanged interface which bind expose

**Comment by Noggog** [comment]
Yeah, I agree a UI should bind to a ObservableCollectionExtended for all the GUI bells and whistles.  What about a non-GUI user, though, that just wants to treat it like a normal IList that just happens to also fire events when things change.  If someone wants to check the list for something, then maybe remove an index if some condition happens, is categorically SourceList not viable for this?  I feel like the only reason it can't be used this way, currently, is because its API is bare bones.

**Comment by RolandPheasant** [comment]
Bare bones! It has been developed over 10 years and does exactly what it is designed to do.

**Comment by RolandPheasant** [comment]
There are loads of resources and examples out there. Here is an example of doing exactly what I believe you want to do

https://github.com/RolandPheasant/DynamicData.Snippets/blob/master/DynamicData.Snippets/Group/XamarinFormsGrouping.cs

**Comment by glennawatson** [comment]
The SourceList is very focused around group of operations and working if possible in reactive ways. So very different paradigm to your traditional containers. Hence the use of other containers for interop

**Comment by Noggog** [comment]
Apologies!  Haha.  Definitely an overly harsh word flippantly tossed into the wrong context.  I'm sorry for that.  I'm aware any design choices are intentional and meant to steer users towards a specific use cases.  I'm asking probing questions just to learn why they are the way they are.

I think glenn's mention that SourceList is "meant for only inside as private in a class" piqued my interest as to why this was the case and confused me a little.  I also remember personally having to wrap my SourceLists in a wrapper object that implemented IList and wired to SourceLists's corresponding calls for my own use. That made me wonder if I was misusing it by doing that, and that it shouldn't be used in places/code people would expect IList calls to be made?

Is there an intentional reason SourceList implements most of the IList functionality without implementing IList?  It does make it hard to plug into other existing code that take lists that just can't accept a SourceList only because it doesn't implement the interface.
