### ISSUE TITLE
TransformMany including parent

### ISSUE THREAD

**Issue by grokys** [reactivemarbles/DynamicData#283]
**Is your feature request related to a problem? Please describe.**

I need to do a `TransformMany` to include the parent object, e.g. in LINQ I would do:

```
var result = source.SelectMany(item => item.Children.Select(child => (item, child)))
```

to get a tuple of `(item, child)` for each child. both `source` and `item.Children` are `ObservableCollection<>`s. if I do this in DynamicData:

```
var result = source.TransformMany(item => item.Children.Select(child => (item, child)))
```

then `Children` isn't tracked. I've tried adding a `ToObservableChangeSet` in there, e.g.:

```
var result = source.TransformMany(item => item.Children.ToObservableChangeSet().Transform(child => (item, child)))
```

but there doesn't seem to be an available overload for such a thing.

**Describe the solution you'd like**

Perhaps an overload of `TransformMany` which takes a selector would be a decent solution? The syntax with `ToObservableChangeSet` included in the lambda is a little unwieldy.

**Comment by RolandPheasant** [comment]
Hi @grokys. After a few years where I've been disillusioned with open source as well as being busy with other stuff, my heart is finally back in it and I am clearing the backlog (Over 100 issues now down the 13).

Regarding this one, I am not entirely sure how a tuple could be returned and be listened to for subsequent updates.  There's no overload on TransformMany to accept a change set because I created the logical collection operators for just that (Or, And, Except) which produce a flattened, non-nested result.  However even those operators are limited and need some work.

I see this is a very old issue and suspect you've moved on since. Let me know if we can close it. Otherwise can you explain practically what you are trying to achive.

**Comment by RolandPheasant** [comment]
I'm closing this. If help is still wanted please re-open
