### ISSUE TITLE
Group with IEqualityComparer?

### ISSUE THREAD

**Issue by flagbug** [reactivemarbles/DynamicData#31]
Hey there, I'm looking for an overload of the `Group` function, that takes an `IEqualityComparer`, just like the `GroupBy` function in LINQ and Rx.

Is this something this library should/would/could implement, or is there any other method to achieve this functionality?

**Comment by RolandPheasant** [comment]
Personally with dynamic data, I have never needed an overload for an equality comparer when grouping which is why I have never implement it,  

However I agree that it would be very useful. The first use case I can think of is grouping on a string and passing in a case insensitive comparer.   I will enable this soon. 

To achieve similar results but for different reasons, I have previously created custom structs which have their own equality implemented. For example

```
 myCache.Connect()
      .Group(x=> (CaseInsensitiveString)x.myString)
      ...     .
```

An example of the case insensitive string is here [CaseInsensitiveString.cs](https://github.com/RolandPheasant/TailBlazer/blob/master/Source/TailBlazer.Domain/CaseInsensitiveString.cs).  The reason I tend to do it that way is I define my equality once only and that equality is by default used everywhere.

**Comment by flagbug** [comment]
>  The first use case I can think of is grouping on a string and passing in a case insensitive comparer.

This is exactly my usecase :smile: 

> To achieve similar results but for different reasons, I have previously created custom structs which have their own equality implemented.

Cool, I'll try that, thanks!

**Comment by RolandPheasant** [comment]
Let me know how you get on. Also any further questions probably the best place to catch me is [Dynamic data on gitter](https://gitter.im/RolandPheasant/DynamicData)

**Comment by projecjavascript** [comment]
Hello Roland how are you?

**Comment by RolandPheasant** [comment]
Ancient so closing
