### ISSUE TITLE
TransformMany produces change sets with Reason = Add, should be Reason = Update

### ISSUE THREAD

**Issue by John-MartinMalone** [reactivemarbles/DynamicData#557]
TransformMany produces change sets with Reason = Add, when I expect Reason = Update

The code below shows TransformMany creating 2 Add changesets for the same key, 1234.
I was expecting a single Add followed by an Update, since the key is the same.

```
    Observable.Timer(TimeSpan.Zero, TimeSpan.FromSeconds(.1)).Take(2)
        .ToObservableChangeSet(x => x)
        .TransformMany(x => new[] { (key: 1234, guid: Guid.NewGuid())}, x => x.key)
        .OnItemAdded(x => Console.WriteLine($"Add {x}"))
        .OnItemUpdated((x,y) => Console.WriteLine($"Update {x}"))
        .Subscribe();
```
The output:
```
Add (1234, 5388bd1c-d5df-4e0c-a5a8-994ab59d281d)
Add (1234, 2d604eeb-03f4-4aa9-b560-769a60f12b77)
```

I am using DynamicDate 7.4.11

**Comment by RolandPheasant** [comment]
`TransformMany` is a limited operator and was never intended to be used for anything except child collections which belong to an object which has an immutable key and a child collection. The reason is that the internals of the implementation rely on using the key which resides on the underlying object.  When the key is transformed the link to the original object is lost and the is no way to reconcile it.

There are options however depending on exactly what you are trying to achieved.  One option is to first change the key, then to produce the new collection : 

```
Observable.Timer(TimeSpan.Zero, TimeSpan.FromSeconds(.1)).Take(2)
    .ToObservableChangeSet(x => x)
    .ChangeKey(x => 1234)                                               //The key cannot mutate
    .Transform((value, key) => new[] { (key, guid: Guid.NewGuid()) })   //make the child collection
    .TransformMany(x => x, x => x.key)                                  //now flatten with a transform
    .OnItemAdded(x => Console.WriteLine($"Add {x}"))
    .OnItemUpdated((x, y) => Console.WriteLine($"Update {x}"))
    .Subscribe();
```

or perhaps transform to a flat object then grooup.

```
Observable.Timer(TimeSpan.Zero, TimeSpan.FromSeconds(.1)).Take(2)
	.ToObservableChangeSet(x => x)
	.Transform(x => (key: 1234, guid: Guid.NewGuid()))
	.GroupWithImmutableState(x => x.key)
	.OnItemAdded(x => Console.WriteLine($"Add {x}"))
	.OnItemUpdated((x, y) => Console.WriteLine($"Update {x}"))
	.Subscribe();

```

**Comment by RolandPheasant** [comment]
Closing owing to explanation above
