### ISSUE TITLE
[Bug]: DisposeMany() suppresses exceptions

### ISSUE THREAD

**Issue by seanreid1201** [reactivemarbles/DynamicData#668]
### Describe the bug 🐞

Calling DisposeMany() on an IObservable<IChangeSet<T>> prevents exceptions propagating out to the caller.
See the test case provided below.
If the call to DisposeMany is omitted, the test passes.

### Step to reproduce

    [Fact]
    public void ExceptionsArePropagated()
    {
        var source = new SourceList<int>();
        source.Add(1);

        var transformed = source
            .Connect()
            .Transform<int, int>(_ => throw new InvalidCastException())
            .DisposeMany();

        FluentActions.Invoking(() => transformed.Subscribe()).Should().Throw<InvalidCastException>();
    }

### Reproduction repository

My work VPN prevents access to github via git

### Expected behavior

When an exception is thrown from within the observable, and not handled by the caller, it should propagate out.

### IDE

Visual Studio 2022

### DynamicData Version

7.12.1

**Comment by RolandPheasant** [comment]
Thanks for reporting this. I'll take a look soon

**Comment by seanreid1201** [comment]
I've taken some time to look into this.
In `DynamicData.List.Internal.OnBeingRemoved<T>`, line 35, it does this:
```
var subscriber = _source.Synchronize(locker).Do(changes => RegisterForRemoval(items, changes), observer.OnError).SubscribeSafe(observer);
```
If this is changed to:
```
var subscriber = _source.Synchronize(locker).Do(changes => RegisterForRemoval(items, changes), ).Subscribe(observer);
```
then the exception bubbles out.

However, from a quick search of the code, it appears that SubscribeSafe is used in many places so other methods will also exhibit this behaviour (for example, I found that RefCount also suppresses errors).

I imagine it is likely then that you will say that this behaviour will not change.

If that's the case, is there something I can do on the outside to make the exceptions on the OnError channel throw?
I've tried various things, but they all seem to just get suppressed.
For example, in the test case I provided, if you subscribe like:
```
transformed.Subscribe(x => { }, ex => throw new Exception(), () => { });
```
the exception is still swallowed.

**Comment by RolandPheasant** [comment]
Exceptions should propagate. Let's not rush into changing everything, but it probably should be done.

**Comment by JakenVeina** [comment]
Exceptions aren't not-propagating, they're just being emitted via `OnError()` within the stream, instead of throwing out of `.Subscribe()`. I think this is definitely the correct approach.

In my mind, `.Subscribe()` should not throw this exception, since it's the result of emitting values into the stream, not a result of some failure to construct observable objects that make up the stream. I.E. it's not the responsibility of `.Subscribe()` to notify the caller of data issues.

Alternatively, consider this realistic scenario:

```cs
var subscription = source
    .Transform(item => new MyDisposable(name: item.Name.ToUpper()))
    .DisposeMany();
```

Let's say that we have a bug where `item.Name` might be `null`, so this transform could throw `NullReferenceException`. Today, we can be assured that such an exception will always be published via `OnError()`. If we were to make the requested change here, that would no longer be guaranteed. Instead, the exception might manifest two different ways, depending on the state of the data in the source at the time of `.Subscribe()`, making it more cumbersome for consumers to deal with.

Additionally, if the exception throws out of `.Subscribe()` it becomes essentially impossible to recover from. The stream that the caller was trying to construct can never be constructed, without clearing out the bogus data from the source. If the exceptions are published via `OnError()` there's mechanisms to handle those errors without killing the entire stream.

**Comment by JakenVeina** [comment]
@RolandPheasant this should now be resolved.
